# -*- coding: utf-8 -*-
"""Taruns.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lenvSqmZ_KJDHyicU4bZ3PvpR0xxkwo4
"""

import numpy as np
import sklearn
from sklearn import linear_model
height = [[4.0], [5.0], [6.0], [7.0], [8.0], [9.0], [10.0]]
weight = [8, 10, 12, 14, 16, 18, 20]
reg = linear_model.LinearRegression()
reg.fit(height, weight)
X_height = [[12.0]]
print(reg.predict(X_height))

import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import make_pipeline
x = [[4.0], [5.0], [6.0], [7.0], [8.0], [9.0], [10.0]]
y = [16, 25, 36, 49, 64, 81, 100]
lin_reg = LinearRegression()
lin_reg.fit(x, y)
print("Linear Regression prediction for x=11:", lin_reg.predict([[11]]))
polynomial_regression = make_pipeline(
PolynomialFeatures(degree=2, include_bias=False),
LinearRegression()
)
polynomial_regression.fit(x, y)
x_new = [[20.0]]
target_predicted = polynomial_regression.predict(x_new)
print("Polynomial Regression prediction for x=20:", target_predicted)